version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hw
    ports:
      - "5432:5432"
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql