server:
  port: 8081
spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: payments_schema

integration:
  products:
    product-executor:
      url: "http://localhost:8080/product"
      connect-timeout: 1s
      read-timeout: 30s
